### ISSUE TITLE
Bug - Nested Count fields incomplete in ConfigItemGet GenericInterface response

### ISSUE THREAD

**Issue by gpregger-ethz** [znuny/ITSMConfigurationManagement#7]
### Expected behavior

With a ConfigItem definition like this (a "Count.." field nested in another "Count..." field):
```yaml
- Key: parent_count_field
  Name: Parent Count Field
  CountDefault: 1
  CountMin: 1
  CountMax: 4
  Input:
    Type: GeneralCatalog
    Class: GC::CLASS1
    Required: 1
  Searchable: 1
  Sub:
  - Key: child_count_field
    Name: Child Count Field
    CountDefault: 0
    CountMax: 4
    CountMin: 0
    Input:
      Required: 1
      Type: Text
```
All defined instances of the child_count_field should be contained as an array in the response from a call to the ConfigItemGet GenericInterface operation.

### Actual behavior

Only the last entry of the child count field is delivered as a string from a call to the ConfigItemGet GenericInterface Operation.

### How to reproduce

1. Create a CI definition with a nested count field (not sure if the parent also needs to be a count field, but in our test it was).
2. Define a ConfigItem with multiple entries for the child_count_field
3. Define a REST Webservice with a ConfigItemGet operation
4. Launch request like this:  
```python
import requests
import json

data = {
  'SessionID': session_id,
  'ConfigItemID': id_of_previously_created_configitem
}

response = requests.post(
  url='https://your.znuny.org/webservicexy/ConfigItemGet',
  headers={'Accept': 'application/json',  'Content-Type': 'application/json'},
  data=json.dumps(data)
```

### Environment

- OS: RHEL 9.5
- OTRS version: 6.5.14 LTS

### Additional information

It appears the culprit is Kernel/GenericInterface/Operation/ConfigItem/Common.pm:InvertFormatXMLData.

With some logging it seemed that before the XMLData is sent to InvertFormatXMLData, all desired information is contained in the Hash, but it's no longer present in the XMLData returned from InvertFormatXMLData.
